name: Khan Soh
short_title: Khan Soh | SE & DS
title: Khan Soh | Full-stack Developer & Data Scientist

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://wksoh.com" # the base hostname & protocol for your site, e.g. http://example.com
logo: "img/favicon.png"
email: "ksoh@tuta.io"
cover: "https://wksoh.com/img/featured/og.jpg"

blog_enabled: false
description: >- # this means to ignore newlines until "email:". Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description.
  I'm Khan Soh, a design minded Full-stack Engineer & Data Scientist focused on developing user-friendly apps & products.
keywords: "ksoh, web, web development, ai, datascience, javascript, singapore, malaysia, flutter, apps, mobile apps"
social:
  - title: email
    feather_icons: mail
    url: mailto:ksoh@tuta.io
  - title: github
    feather_icons: github
    url: https://github.com/notaunty
  - title: linkedin
    feather_icons: linkedin
    url: https://www.linkedin.com

source: src
destination: ./_site

sass:
  style: compressed
  sourcemap: never
  sass_dir: _sass


collections_dir: collections

collections:
  blog:
    output: true
    permalink: /:collection/:title


exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - package.json

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
